### ISSUE TITLE
network mode of tf_docker_sdk

### ISSUE THREAD

**Issue by itspjc** [BMW-InnovationLab/BMW-TensorFlow-Training-GUI#11]
Thank you for sharing your great repository for me. I want to know the reason why you set only network mode of tf_docker_sdk as "host" while the others belong to bridge network. 

Thanks.

**Comment by JoeSL** [comment]
Hello, 

Thank you for your interest in the repository.

The reason behind that decision was the fact that users need to specify 2 port numbers one for the training api and one for tensorboard.
In order to avoid selecting already used ports and cause errors there is a small script inside tf_docker_sdk that checks open ports so user can only select from then hence minimizing user input error.
Since tf_docker_sdk is now required to see the host ports, the network mode has been set to host.
