### ISSUE TITLE
unpack requires a buffer of 2 bytes

### ISSUE THREAD

**Issue by localhost-server** [BMW-InnovationLab/BMW-TensorFlow-Training-GUI#60]
getting this popup while training any model over sordi dataset

**Comment by hadikoub** [comment]
Hello,

Unfortunately, we cannot help you if you provide us only the following message `unpack requires a buffer of 2 bytes`

It would be great if you could fill in the following info:

### Describe the bug

A clear and concise description of what the bug is.

### Steps to reproduce

Steps to reproduce the behavior.

### Additional context

Include any logs that would be helpful in diagnosing the problem.

- Network used 
- Logs
- Which component generates this error (GUI, docker_sdk_api, training_api, inference_api, ...)
- On which step this error is appearing 

### System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by localhost-server** [comment]
system information
ubuntu 18.04 cuda11.7 gpu nvidia gtx 1650 4gb

Additional context
network used  centernet_resnet101_v1_fpn_512x512 or any other 
component generating error can't be determined cause getting popup while clicking done in hyper parameters
I have tried it multiple times build the docker environment multiple times but getting the same issue and model doesn't train any further .
