### ISSUE TITLE
when starting the test training i get unknown error 

### ISSUE THREAD

**Issue by KiriUbu** [BMW-InnovationLab/BMW-TensorFlow-Training-GUI#9]
When i start the test training i get the Error "Unknown Error" 
![3](https://user-images.githubusercontent.com/47858105/75157182-e2d7a580-5713-11ea-9fe4-32d531701215.png)

I had no errors during the installation. I am using Ubuntu 18.04.4 LTS what a i doing wrong? 

thank you for every suggestion

**Comment by JoeSL** [comment]
A good way to debug the problem would be to check the api container logs. 
Open your terminal and type **docker ps** you should see a docker container named docker belonging to an image called tf_docker_sdk
Take the id of that container and type **docker logs _the id you just copied_**.
This should give you a clearer idea on why the training failed.

**Comment by KiriUbu** [comment]
Thank you i will try it.

**Comment by Gothryd** [comment]
@KiriUbu @JoeSL 

Does somebody have solve it?
Error in my sdk docker logs is absent until I click "next" button second time (in this case error tell me that container name is already taken), so I guess it should appear somewhere else.

Only uncommon action I performed is running containers via terminals instead of run.yml file as far as runtime string is not supported by newest version of docker-compose

There is commands which I run from 3 different terminals (~/TrainingAPI/ is my API root directory)

`sudo docker run --rm -it --gpus all --net=host -v /var/run/docker.sock:/var/run/docker.sock -v ~/TrainingAPI/datasets:/datasets -v ~/TrainingAPI/training_api/networks_weights:/weights -v ~/TrainingAPI/checkpoints:/checkpoints tf_docker_sdk `

`sudo docker run --rm -it -v /var/run/docker.sock:/var/n/docker.sock -v ~/TrainingAPI/inference/models:/models -v ~/TrainingAPI/inference/src/main:/main -p 4343:4343 tf_inference_api_for_training_gui`

`sudo docker run --rm -it -p 4200:80 tf_training_ui`

Is there something else I should provide?

Also must notice, that new job appears in the job list, and I even could open logs window.

UPD: There is my logs window before error 

![Screenshot from 2020-03-16 17-19-33](https://user-images.githubusercontent.com/37375661/76773029-7dbf1f00-67aa-11ea-9640-7ca0ab0b49fd.png)

**Comment by JoeSL** [comment]
I see that you are using firefox as your browser. We recommend to try a different browser (e.g. chrome, chromium or opera) and see if the problem persists
